import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import TextCarousel from "./components/TextCarousel";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./contexts/AuthContext";
import { CartProvider } from "./contexts/CartContext";
// import BootstrapClient from "./components/BootstrapClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} antialiased`}
      >
        <AuthProvider>
          <CartProvider>
            <TextCarousel />
            <Navbar />
            <main>{children}</main>
            <footer></footer>
            {/* <BootstrapClient /> */}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
